// SPDX-FileCopyrightText: Copyright (C) 2023-2025 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)<lichtblick@bmwgroup.com>
// SPDX-License-Identifier: MPL-2.0

import { LayoutData } from "@lichtblick/suite-base/context/CurrentLayoutContext/actions";
import { defaultPlaybackConfig } from "@lichtblick/suite-base/providers/CurrentLayoutProvider/reducers";

export interface ClassicLayout {
  id?: string;
  name: string;
  description: string;
  data: LayoutData;
}

// 基于现有的default布局创建经典布局列表
export const classicLayouts: ClassicLayout[] = [
  {
    name: "经典布局",
    description: "经典布局",
    data: {
      configById: {
        "Image!3ldryoy": {
          cameraState: {
            distance: 20,
            perspective: true,
            phi: 60,
            target: [0, 0, 0],
            targetOffset: [0, 0, 0],
            targetOrientation: [0, 0, 0, 1],
            thetaOffset: 45,
            fovy: 45,
            near: 0.5,
            far: 5000,
          },
          followMode: "follow-pose",
          scene: {},
          transforms: {},
          topics: {},
          layers: {},
          publish: {
            type: "point",
            poseTopic: "/move_base_simple/goal",
            pointTopic: "/clicked_point",
            poseEstimateTopic: "/initialpose",
            poseEstimateXDeviation: 0.5,
            poseEstimateYDeviation: 0.5,
            poseEstimateThetaDeviation: 0.26179939,
          },
          imageMode: {
            imageTopic: "center_front",
          },
        },
        "Image!35nima4": {
          cameraState: {
            distance: 20,
            perspective: true,
            phi: 60,
            target: [0, 0, 0],
            targetOffset: [0, 0, 0],
            targetOrientation: [0, 0, 0, 1],
            thetaOffset: 45,
            fovy: 45,
            near: 0.5,
            far: 5000,
          },
          followMode: "follow-pose",
          scene: {},
          transforms: {},
          topics: {},
          layers: {},
          publish: {
            type: "point",
            poseTopic: "/move_base_simple/goal",
            pointTopic: "/clicked_point",
            poseEstimateTopic: "/initialpose",
            poseEstimateXDeviation: 0.5,
            poseEstimateYDeviation: 0.5,
            poseEstimateThetaDeviation: 0.26179939,
          },
          imageMode: {
            imageTopic: "surrounding_front",
          },
        },
        "Image!wmabl3": {
          cameraState: {
            distance: 20,
            perspective: true,
            phi: 60,
            target: [0, 0, 0],
            targetOffset: [0, 0, 0],
            targetOrientation: [0, 0, 0, 1],
            thetaOffset: 45,
            fovy: 45,
            near: 0.5,
            far: 5000,
          },
          followMode: "follow-pose",
          scene: {},
          transforms: {},
          topics: {},
          layers: {},
          publish: {
            type: "point",
            poseTopic: "/move_base_simple/goal",
            pointTopic: "/clicked_point",
            poseEstimateTopic: "/initialpose",
            poseEstimateXDeviation: 0.5,
            poseEstimateYDeviation: 0.5,
            poseEstimateThetaDeviation: 0.26179939,
          },
          imageMode: {
            imageTopic: "surrounding_back",
          },
        },
        "Image!2cbarc6": {
          cameraState: {
            distance: 20,
            perspective: true,
            phi: 60,
            target: [0, 0, 0],
            targetOffset: [0, 0, 0],
            targetOrientation: [0, 0, 0, 1],
            thetaOffset: 45,
            fovy: 45,
            near: 0.5,
            far: 5000,
          },
          followMode: "follow-pose",
          scene: {},
          transforms: {},
          topics: {},
          layers: {},
          publish: {
            type: "point",
            poseTopic: "/move_base_simple/goal",
            pointTopic: "/clicked_point",
            poseEstimateTopic: "/initialpose",
            poseEstimateXDeviation: 0.5,
            poseEstimateYDeviation: 0.5,
            poseEstimateThetaDeviation: 0.26179939,
          },
          imageMode: {
            imageTopic: "surrounding_left",
          },
        },
        "Image!yvowl3": {
          cameraState: {
            distance: 20,
            perspective: true,
            phi: 60,
            target: [0, 0, 0],
            targetOffset: [0, 0, 0],
            targetOrientation: [0, 0, 0, 1],
            thetaOffset: 45,
            fovy: 45,
            near: 0.5,
            far: 5000,
          },
          followMode: "follow-pose",
          scene: {},
          transforms: {},
          topics: {},
          layers: {},
          publish: {
            type: "point",
            poseTopic: "/move_base_simple/goal",
            pointTopic: "/clicked_point",
            poseEstimateTopic: "/initialpose",
            poseEstimateXDeviation: 0.5,
            poseEstimateYDeviation: 0.5,
            poseEstimateThetaDeviation: 0.26179939,
          },
          imageMode: {
            imageTopic: "surrounding_right",
          },
        },
        "3D!btt89g": {
          cameraState: {
            distance: 19.999999999999982,
            perspective: true,
            phi: 60.634920634920604,
            target: [0, 0, 0],
            targetOffset: [0, 0, 0],
            targetOrientation: [0, 0, 0, 1],
            thetaOffset: 44.99999999999999,
            fovy: 45,
            near: 0.5,
            far: 5000,
          },
          followMode: "follow-pose",
          scene: {},
          transforms: {},
          topics: {},
          layers: {},
          publish: {
            type: "point",
            poseTopic: "/move_base_simple/goal",
            pointTopic: "/clicked_point",
            poseEstimateTopic: "/initialpose",
            poseEstimateXDeviation: 0.5,
            poseEstimateYDeviation: 0.5,
            poseEstimateThetaDeviation: 0.26179939,
          },
          imageMode: {},
        },
        "map!2yquqr1": {
          center: {
            lat: 22.737425604433778,
            lon: 114.39959138631822,
          },
          customTileUrl: "",
          disabledTopics: [],
          followTopic: "",
          layer: "map",
          topicColors: {},
          zoomLevel: 18,
          maxNativeZoom: 18,
        },
        "Plot!odoa1n": {
          paths: [],
          showXAxisLabels: true,
          showYAxisLabels: true,
          showLegend: true,
          legendDisplay: "floating",
          showPlotValuesInLegend: false,
          isSynced: true,
          xAxisVal: "timestamp",
          sidebarDimension: 240,
        },
        "Plot!9oekxl": {
          paths: [],
          showXAxisLabels: true,
          showYAxisLabels: true,
          showLegend: true,
          legendDisplay: "floating",
          showPlotValuesInLegend: false,
          isSynced: true,
          xAxisVal: "timestamp",
          sidebarDimension: 240,
        },
        "Plot!1heu8z7": {
          paths: [],
          showXAxisLabels: true,
          showYAxisLabels: true,
          showLegend: true,
          legendDisplay: "floating",
          showPlotValuesInLegend: false,
          isSynced: true,
          xAxisVal: "timestamp",
          sidebarDimension: 240,
        },
        "Plot!3f7r6p3": {
          paths: [],
          showXAxisLabels: true,
          showYAxisLabels: true,
          showLegend: true,
          legendDisplay: "floating",
          showPlotValuesInLegend: false,
          isSynced: true,
          xAxisVal: "timestamp",
          sidebarDimension: 240,
        },
      },
      globalVariables: {},
      userNodes: {},
      playbackConfig: {
        speed: 1,
      },
      layout: {
        first: {
          first: {
            first: "Image!3ldryoy",
            second: {
              first: "Image!35nima4",
              second: {
                first: "Image!wmabl3",
                second: {
                  first: "Image!2cbarc6",
                  second: "Image!yvowl3",
                  direction: "row",
                  splitPercentage: 50.19531250000002,
                },
                direction: "row",
                splitPercentage: 33.592736705577174,
              },
              direction: "row",
              splitPercentage: 25.000000000000007,
            },
            direction: "row",
            splitPercentage: 20.062208398133752,
          },
          second: {
            first: "3D!btt89g",
            second: "map!2yquqr1",
            direction: "row",
            splitPercentage: 71.74133014442093,
          },
          direction: "column",
          splitPercentage: 27.636363636363637,
        },
        second: {
          first: {
            first: "Plot!odoa1n",
            second: "Plot!9oekxl",
            direction: "column",
          },
          second: {
            first: "Plot!1heu8z7",
            second: "Plot!3f7r6p3",
            direction: "column",
          },
          direction: "column",
        },
        direction: "row",
        splitPercentage: 77.67857142857143,
      },
    },
  },
  {
    name: "默认布局",
    description: "包含3D视图、图像面板和原始消息面板的标准布局",
    data: {
      configById: {
        "3D!18i6zy7": {
          layers: {
            "845139cb-26bc-40b3-8161-8ab60af4baf5": {
              visible: true,
              frameLocked: true,
              label: "Grid",
              instanceId: "845139cb-26bc-40b3-8161-8ab60af4baf5",
              layerId: "foxglove.Grid",
              size: 10,
              divisions: 10,
              lineWidth: 1,
              color: "#248eff",
              position: [0, 0, 0],
              rotation: [0, 0, 0],
              order: 1,
            },
          },
        },
        "RawMessages!os6rgs": {},
        "Image!3mnp456": {},
      },
      globalVariables: {},
      userNodes: {},
      playbackConfig: { ...defaultPlaybackConfig },
      layout: {
        first: "3D!18i6zy7",
        second: {
          first: "Image!3mnp456",
          second: "RawMessages!os6rgs",
          direction: "column",
          splitPercentage: 30,
        },
        direction: "row",
        splitPercentage: 70,
      },
    },
  },
  {
    id: "classic__3d",
    name: "3D视图布局",
    description: "专注于3D可视化的布局，适合机器人导航和路径规划",
    data: {
      configById: {
        "3D!18i6zy7": {
          layers: {
            "845139cb-26bc-40b3-8161-8ab60af4baf5": {
              visible: true,
              frameLocked: true,
              label: "Grid",
              instanceId: "845139cb-26bc-40b3-8161-8ab60af4baf5",
              layerId: "foxglove.Grid",
              size: 20,
              divisions: 20,
              lineWidth: 1,
              color: "#248eff",
              position: [0, 0, 0],
              rotation: [0, 0, 0],
              order: 1,
            },
          },
        },
      },
      globalVariables: {},
      userNodes: {},
      playbackConfig: { ...defaultPlaybackConfig },
      layout: {
        first: "3D!18i6zy7",
        second: "RawMessages!os6rgs",
        direction: "row",
        splitPercentage: 100,
      },
    },
  },
  {
    name: "数据分析布局",
    description: "包含多个图表面板，适合数据分析和监控",
    data: {
      configById: {
        "Plot!chart1": {},
        "Plot!chart2": {},
        "RawMessages!messages": {},
      },
      globalVariables: {},
      userNodes: {},
      playbackConfig: { ...defaultPlaybackConfig },
      layout: {
        first: {
          first: "Plot!chart1",
          second: "Plot!chart2",
          direction: "row",
          splitPercentage: 50,
        },
        second: "RawMessages!messages",
        direction: "column",
        splitPercentage: 60,
      },
    },
  },
  {
    name: "图像处理布局",
    description: "专注于图像处理和计算机视觉的布局",
    data: {
      configById: {
        "Image!camera1": {},
        "Image!camera2": {},
        "RawMessages!imageData": {},
      },
      globalVariables: {},
      userNodes: {},
      playbackConfig: { ...defaultPlaybackConfig },
      layout: {
        first: {
          first: "Image!camera1",
          second: "Image!camera2",
          direction: "row",
          splitPercentage: 50,
        },
        second: "RawMessages!imageData",
        direction: "column",
        splitPercentage: 70,
      },
    },
  },
  {
    name: "调试布局",
    description: "包含诊断面板和原始消息，适合系统调试",
    data: {
      configById: {
        "DiagnosticStatus!status": {},
        "RawMessages!diagnostics": {},
        "RawMessages!system": {},
      },
      globalVariables: {},
      userNodes: {},
      playbackConfig: { ...defaultPlaybackConfig },
      layout: {
        first: "DiagnosticStatus!status",
        second: {
          first: "RawMessages!diagnostics",
          second: "RawMessages!system",
          direction: "column",
          splitPercentage: 50,
        },
        direction: "row",
        splitPercentage: 40,
      },
    },
  },
];
